import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";
import DynamicManifest from "./components/DynamicManifest";


export const metadata: Metadata = {
  title: "X Fun",
  description: "Fun and engaging content for curious minds",
  // Twitter now returns 403 for hotlinked videos when a third-party Referer is present.
  // Using a no-referrer policy fixes direct video.twimg.com playback without a server proxy.
  referrer: "no-referrer",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "X Fun",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: "/icon.svg",
    apple: "/apple-icon.png",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#1da1f2",
>>>>>>> 6d8c2a5b4716c4e1ec28fd841fb832a75ffd5ae6
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
        className="antialiased"
      >
        <DynamicManifest />
>>>>>>> 6d8c2a5b4716c4e1ec28fd841fb832a75ffd5ae6
        {children}
      </body>
    </html>
  );
}
